# Generated by Django 5.1.3 on 2024-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
