# Generated by Django 5.1.3 on 2024-12-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courseapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
