# Generated by Django 5.1.3 on 2024-12-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_grades_time_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
